tap "adoptopenjdk/openjdk"
tap "buo/cask-upgrade"
tap "derailed/k9s"
tap "eddieantonio/eddieantonio"
tap "fluidkeys/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jmacdonald/amp"
tap "mongodb/brew"
tap "neovim/neovim"
tap "petere/postgresql"
tap "thoughtbot/formulae"
brew "libyaml"
brew "openssl@1.1"
brew "ansible"
brew "apr"
brew "apr-util"
brew "aspell"
brew "autoconf"
brew "autojump"
brew "automake"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "bash"
brew "binutils"
brew "bison@2.7"
brew "boost"
brew "brew-php-switcher"
brew "c-ares"
brew "libffi"
brew "cmake"
brew "curl"
brew "unixodbc"
brew "libpq"
brew "composer"
brew "consul-template"
brew "coreutils"
brew "ctags"
brew "diff-so-fancy"
brew "diffutils"
brew "direnv"
brew "dnsmasq", restart_service: true
brew "docker", link: false
brew "docker-compose"
brew "docker-machine", restart_service: true, link: false
brew "duck"
brew "ed", link: true
brew "exiftool"
brew "expect"
brew "fasd"
brew "lz4"
brew "snappy"
brew "ffmpeg"
brew "flex"
brew "fzf"
brew "gawk"
brew "gh"
brew "git"
brew "git-extras"
brew "git-flow"
brew "git-ftp"
brew "git-lfs"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "gnupg", link: false
brew "gnuplot"
brew "graphviz"
brew "grep"
brew "gzip"
brew "helm"
brew "htop"
brew "httpd"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "iperf3"
brew "iproute2mac"
brew "ipython"
brew "ispell"
brew "jansson"
brew "jid"
brew "jmeter"
brew "jq"
brew "jupyterlab"
brew "keychain"
brew "kotlin"
brew "kubectx"
brew "lastpass-cli"
brew "lazydocker"
brew "libev"
brew "libxml2"
brew "libxslt"
brew "makedepend"
brew "mas"
brew "maven"
brew "memcached", restart_service: true
brew "mkcert"
brew "protobuf"
brew "mosh"
brew "mtr"
brew "mycli"
brew "mysql@5.7", link: true
brew "neovim"
brew "nghttp2"
brew "openconnect"
brew "openssh"
brew "openssl@3", link: true
brew "ossp-uuid"
brew "postgresql"
brew "pg_top"
brew "pgcli"
brew "pianobar", link: false
brew "pipx"
brew "postgresql@10"
brew "pspg"
brew "pstree"
brew "pwgen"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python@3.8"
brew "qcachegrind"
brew "qt"
brew "r"
brew "raptor"
brew "re2c"
brew "reattach-to-user-namespace"
brew "redis"
brew "ripgrep"
brew "s3cmd"
brew "scala"
brew "shellcheck"
brew "spdylay"
brew "ssh-copy-id", link: true
brew "sslmate"
brew "stern"
brew "telnet"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "translate-toolkit"
brew "v8"
brew "vim"
brew "virtualenv"
brew "watch"
brew "wdiff"
brew "wget"
brew "xmlstarlet"
brew "yarn", link: false
brew "zlib"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "derailed/k9s/k9s"
brew "eddieantonio/eddieantonio/imgcat"
brew "heroku/brew/heroku"
brew "jmacdonald/amp/amp"
brew "thoughtbot/formulae/rcm"
cask "adobe-acrobat-reader"
cask "adobe-air"
cask "adoptopenjdk10"
cask "adoptopenjdk11"
cask "adoptopenjdk12"
cask "adoptopenjdk9"
cask "air-video-server-hd"
cask "atom"
cask "azure-data-studio"
cask "basecamp"
cask "boostnote"
cask "charles"
cask "chromedriver"
cask "cyberduck"
cask "discord"
cask "dosbox"
cask "ferdi"
cask "firefox"
cask "font-hack"
cask "franz"
cask "gimp"
cask "gpg-suite"
cask "insomnia"
cask "iterm2"
cask "jdiskreport"
cask "jetbrains-toolbox"
cask "keka"
cask "licecap"
cask "macdown"
cask "minitimer"
cask "mono-mdk-for-visual-studio"
cask "mysqlworkbench"
cask "ngrok"
cask "openemu"
cask "osquery"
cask "phantomjs"
cask "postman"
cask "renamer"
cask "rstudio"
cask "sequel-pro"
cask "signal"
cask "skitch"
cask "skype"
cask "sourcetree"
cask "spotify"
cask "sqlworkbenchj"
cask "steam"
cask "sublime-text"
cask "timer"
cask "vagrant"
cask "visual-studio"
cask "visual-studio-code"
cask "vlc"
cask "wechat"
cask "whatsapp"
cask "xampp"
mas "1Keyboard", id: 766939888
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Magnet", id: 441258766
mas "Mobile Mouse Server", id: 412814284
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Simplenote", id: 692867256
mas "Slack", id: 803453959
mas "Time Out", id: 402592703
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
