tap "eddieantonio/eddieantonio"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "jmacdonald/amp"
tap "replicatedhq/replicated"
tap "zyedidia/literate"
brew "openssl"
brew "python@2"
brew "ansible"
brew "autojump"
brew "automake"
brew "bash"
brew "binutils"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "diff-so-fancy"
brew "diffutils"
brew "docker-machine"
brew "ed", args: ["with-default-names"]
brew "expect"
brew "fasd"
brew "findutils", args: ["with-default-names"]
brew "gettext", link: true
brew "gawk"
brew "git"
brew "git-lfs"
brew "gnu-indent", args: ["with-default-names"]
brew "gnu-sed"
brew "gnu-tar", args: ["with-default-names"]
brew "gnu-which", args: ["with-default-names"]
brew "gnutls"
brew "gnupg"
brew "graphviz"
brew "grep", args: ["with-default-names"]
brew "gzip"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "iperf3"
brew "jq"
brew "jupyter"
brew "lastpass-cli", args: ["with-pinentry"]
brew "libpq"
brew "lz4"
brew "maven"
brew "memcached", restart_service: true
brew "mongodb"
brew "mosh"
brew "mtr"
brew "mysql"
brew "openconnect"
brew "openssh"
brew "openssl@1.1"
brew "pianobar"
brew "pkg-config"
brew "postgresql"
brew "pstree"
brew "pwgen"
brew "pyenv"
brew "pyenv-virtualenv"
brew "qt"
brew "qcachegrind", args: ["with-graphviz"]
brew "r"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "ripgrep"
brew "shellcheck"
brew "snappy"
brew "ssh-copy-id"
brew "telnet"
brew "the_silver_searcher"
brew "tmux"
brew "translate-toolkit"
brew "vim"
brew "watch"
brew "wdiff", args: ["with-gettext"]
brew "wget"
brew "wxmac", args: ["with-static", "with-stl"]
brew "xmlstarlet"
brew "yarn"
brew "zsh"
brew "eddieantonio/eddieantonio/imgcat"
brew "heroku/brew/heroku"
brew "replicatedhq/replicated/cli"
cask "adobe-acrobat-reader"
cask "atom"
cask "chromedriver"
cask "cyberduck"
cask "docker"
cask "eclipse-installer"
cask "flux"
cask "franz"
cask "google-backup-and-sync"
cask "iterm2"
cask "jetbrains-toolbox"
cask "jing"
cask "lastpass"
cask "licecap"
cask "macdown"
cask "mysqlworkbench"
cask "nomachine"
cask "oni"
cask "postman"
cask "recordit"
cask "rstudio"
cask "skitch"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "time-out"
cask "virtualbox"
cask "vlc"
cask "whatsapp"
